(test
 (name test_easy_xlsx_docs)
 (modules test_easy_xlsx_docs)
 (libraries csv easy_xlsx ounit2)
 (deps
  (source_tree files))
 (preprocess
  (pps ppx_jane)))

(test
 (name test_easy_xlsx_formats)
 (modules test_easy_xlsx_formats)
 (libraries csv easy_xlsx ounit2)
 (deps
  (source_tree files))
 (preprocess
  (pps ppx_jane)))
