version: 2.1

jobs:
  build:
    docker:
      - image: ocaml/opam:debian-12-ocaml-5.2
    environment:
      TERM: xterm
    steps:
      - checkout
      - run:
          name: Update opam
          command: opam update
      - run:
          name: Pin packages
          command: |
            opam pin add -y -n open_packaging .
            opam pin add -y -n spreadsheetml .
            opam pin add -y -n easy_xlsx .
      - run:
          name: Install dependencies
          command: opam install --deps-only -y -t easy_xlsx open_packaging spreadsheetml
      - run:
          name: Build
          command: opam exec -- dune build
      - run:
          name: Test
          command: opam exec -- dune runtest

workflows:
  build-and-test:
    jobs:
      - build
